import "./globals.css";
import App from "./App";
import "./globalicons.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import AuthProvider from "@/contexts/AuthProvider";
import ThemeProvider from "@/contexts/ThemeProvider";
import ClientProvider from "@/contexts/ClientProvider";
import ProductProvider from "@/contexts/ProductProvider";
import NotificationProvider from "@/contexts/NotificationProvider";
import InvoiceProvider from "@/contexts/InvoiceProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <NotificationProvider>
            <AuthProvider>
              <ClientProvider>
                <ProductProvider>
                  <InvoiceProvider>
                    <App>
                      {children}
                    </App>
                  </InvoiceProvider>
                </ProductProvider>
              </ClientProvider>
            </AuthProvider>
          </NotificationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
