import "./globals.css";
import "./globalicons.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import App from "./App";
import AuthProvider from "@/contexts/AuthProvider";
import ThemeProvider from "@/contexts/ThemeProvider";
import NotificationProvider from "@/contexts/NotificationProvider";
import ClientProvider from "@/contexts/ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <NotificationProvider>
            <AuthProvider>
              <ClientProvider>
                <App>
                  {children}
                </App>
              </ClientProvider>
            </AuthProvider>
          </NotificationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
